### PR TITLE
Implement new homepage design and responsiveness

### PR DESCRIPTION
**Pull request by whunter**
add fonts, more styling

more hero styles

moar stylezzzz

remove shadow

COMPEL not Compel

search and fix root_path stuff

more styles

collections section

explore collections list

photo caption

start footer

homepage responsiveness

make search form readable

footer nav

### CODE REVIEW

**Comment by shabububu** [comment]
I may be missing the new fonts. Let me see if I can locate them. [Edit: To clarify, I think I need the new fonts to test locally, but I don't mean to check them in.]

**Comment by shabububu** [comment]
I got updated fonts from Lee, but the "Raleway" fonts aren't quite looking like I would expect. I'm attaching a screenshot of what I'm seeing. Maybe there's something off about my local environment? I'm definitely not experienced with playing around with fonts. 

screen shot 2018-06-26 at 10 57 37 am

**Comment by shabububu** [comment]
I think I'm able to get the Raleway fonts to load, but I had to do the following:

* Copy over the Raleway fonts from: https://github.com/google/fonts/tree/master/ofl/raleway/*.ttf
* Modify `app/assets/stylesheets/vtul/fonts.scss` to use `url` instead of `font-url`

It now looks a lot like the mockups (screenshots taken in two sections):
screen shot 2018-06-26 at 5 50 38 pm
screen shot 2018-06-26 at 5 50 50 pm

**Comment by shabububu** [comment]
The fonts load for me now with the commit 2213a8b. Overall, the homepage looks fine. It seems to have the styles and appearance of the mock-up. The only thing I noticed that I might change eventually is that the `hero-fg-text` and `hero-highlighted-text` appear to extend too far right beyond the rest of the homepage. I wouldn't hold up the PR for this, but maybe open up another ticket for cleanup later if there's time.

Also, the Collections section looks as I would expect:
screen shot 2018-07-06 at 9 47 48 am

Everything else looks good -- group PR Review with @whunter @tingtingjh.

**Review by tingtingjh — APPROVED** [review]
I tested the code and joined group PR review. I approve.

**Review by shabububu — APPROVED** [review]
Recent modification to trim hero elements look good! I approve.

**Pull request merged**
