### PR TITLE
Make tinyMCE thingy work for descriptions

### PR DESCRIPTION
**Pull request by whunter**
**Makes tinyMCE editor work for composition description which is multi-valued**
* * *

**JIRA Ticket**: (https://webapps.es.vt.edu/jira/browse/LIBTD-1479) (:star:)

# What does this Pull Request do? (:star:)
Addresses bug in tinyMCE initialization in multi-valued fields

# What's the changes? (:star:)
Addresses bug in tinyMCE initialization in multi-valued fields

# How should this be tested?
* Create a composition with multiple entries in description and ensure it works

# Additional Notes:
* branch: LIBTD-1479

# Interested parties
@tingtingjh @shabububu 

(:star:) Required fields

### CODE REVIEW

**Review by tingtingjh — CHANGES_REQUESTED** [review]
textarea with performance_description id should also be updated accordingly

**Comment by whunter** [comment]
@tingtingjh sorry about that. I changed it so that it should support performances as well now. Thanks!

**Comment by shabububu** [comment]
From a functional point of view, it seems to work fine. I am able to create multiple descriptions for performances and compositions using the tinyMCE.

One issue that I noticed is that new tinyMCE text boxes aren't always the same size as the previous ones. The new text boxes can potentially be obstructed from the view depending on the size of the browser window or device. This is the only issue that I can see.

screen shot 2018-08-10 at 11 20 51 am

**Comment by whunter** [comment]
@shabububu I made the width of the editor fluid so it should render the same width as the ones that are already there. Thanks for catching that!

**Comment by tingtingjh** [comment]
@whunter How about the description field for a Collection?

**Comment by whunter** [comment]
@tingtingjh I've now added support for collection descriptions. Thank you for catching that.

**Review by tingtingjh — APPROVED** [review]
I tried the description field with tinymce editor on Collection, Performance and Composition, they all look good to me.

**Pull request merged**
