### PR TITLE
add about page

### PR DESCRIPTION
**Pull request by whunter**

### CODE REVIEW

**Comment by yinlinchen** [comment]
How about add the disclaimer statements about the external links (if not
already there)?

**Review by shabububu — APPROVED** [review]
The About page is what I expected based on the Hyrax 1.0.3 version. I approve.

**Comment by shabububu** [comment]
Actually, I just thought of something. An admin can update the "About" page via the admin dashboard options in the vanilla Hyrax application. It's still there in COMPEL, but it doesn't seem to do anything. Should we remove the admin option to edit the About page if we want to keep the About page static?

screen shot 2018-07-11 at 9 02 45 am

I have no real problem with the code that was added with this PR, but maybe we should consider opening up another ticket to remove this option for admins.

**Comment by whunter** [comment]
@yinlinchen I was planning on putting a disclaimer on the "show" pages where the links are rendered but I think you're right, it might be a good idea to put it here too.

@shabububu Agreed, I'll pull the about option out of the pages controller.

**Comment by whunter** [comment]
@yinlinchen @shabububu I just pushed changes based on both of your suggestions. Thanks! :)

**Comment by shabububu** [comment]
Looks good to me. I'll squash and merge.

**Pull request merged**
