### PR TITLE
accessibility changes

### PR DESCRIPTION
**Pull request by whunter**
**COMPEL accessibility changes**
* * *

**JIRA Ticket**: (https://webapps.es.vt.edu/jira/browse/LIBTD-1326) (:star:)

# What does this Pull Request do? (:star:)
This pull request makes updates the COMPEL design to be more accessible to users with different abilities. 

# What's the changes? (:star:)
* increased font sizes
* increased color contrast
* modifies alt-text
* fixes navbar rendering for smaller screensizes and navbar toggle button functionality

# How should this be tested?
* Check to make sure that text is legible and increased size doesn't cause any problems. 
* Test navbar by resizing your browser window. Under 1150px the navbar should disappear and a toggle button should appear top left. Click toggle button to open and close navbar.

### CODE REVIEW

**Review by tingtingjh — APPROVED** [review]
The site looks good with increased font size and color changes. The navbar behaviors responsively as intended: under 1150px, I can toggle the buttons to open and close the menu bar.

**Comment by shabububu** [comment]
I tried using some of the chrome emulators. I think one of the navigation bars is disappearing for me. 

Browser view (nav bar shows "About", "Browse", etc.):
screen shot 2018-07-27 at 5 41 57 am
Pixel 2 view (missing comparable nav bar):
screen shot 2018-07-27 at 5 42 28 am

**Comment by shabububu** [comment]
Ah, I understand now. That's intentional. I can see that "hamburger" icon appear now.

**Comment by shabububu** [comment]
Okay, I think this one might be worth looking into. Some versions of iPhones in the chrome emulator get cut off. 

screen shot 2018-07-27 at 5 55 40 am

`iPhone 5/SE` looks way worse, but maybe that's too old for us to worry about?

**Comment by shabububu** [comment]
I initially tried using the chrome emulator with other phones/devices, but there are articles describing inaccuracies when using it compared to a real device, so I'm disregarding those and deleting previous comments about that. 

I tried it out on chrome and safari. And, I can see the hamburger menu too when I reduce the size of the browser. Visually, the fonts appear to be big enough and have enough contrast to me. As far as I can tell, it looks good.

Edit: 

Also, I can see the image alt tag on the home page when I inspect it, so I'm guessing that's good. I see the updated alt tag of the title on the listing of works images from my dashboard. However, do we need to have those alt tags modified everywhere? When I do a blank search from the home page, the search results don't have alt tags that are as useful (i.e., id instead of title).

I think there might be a responsive design issue.  From the dashboard, if I make the browser small, the search box bleeds into the section below.

screen shot 2018-07-27 at 8 42 36 am

Similarly, the "Computer Music Library" next to the search box from the dashboard may also bleed into the section below when resizing and potentially obscure text/links.

**Comment by shabububu** [comment]
The dashboard page responsiveness looks a lot better to me now. I approve.

**Review by shabububu — APPROVED** [review]

**Pull request merged**
